### PR TITLE
Reset Appium context if orientation getting is failed

### PR DESCRIPTION
**Pull request by valfirst**

### CODE REVIEW

**Comment by valfirst** [comment]
@danielputerman, could you please review the changes?

**Comment by danielputerman** [comment]
Of course :) I'll review and update soon.

**Comment by valfirst** [comment]
@danielputerman, could you please review the changes?

**Comment by danielputerman** [comment]
Hi, I uploaded the updated version (3.8) to maven central. Should be available within a couple of hours.

Thanks!

**Comment by valfirst** [comment]
@danielputerman, thank you!

**Pull request merged**
